"use client";

import { ArrowLeft, BookOpen, Check, CheckSquare, ChevronRight, CircleHelp, Clock3, FileText, LayoutTemplate, Search, ShoppingBag, Sparkles } from "lucide-react";

type UtilityPageType = "Library" | "My Tasks" | "Marketplace" | "Help";

export function UtilityPage({ type, onBack }: { type: UtilityPageType; onBack: () => void }) {
  const config = {
    Library: { icon: BookOpen, eyebrow: "Workspace resources", title: "Library", description: "Keep templates, guides, and reusable building blocks close at hand." },
    "My Tasks": { icon: CheckSquare, eyebrow: "Personal workspace", title: "My Tasks", description: "A focused view of the work that needs your attention." },
    Marketplace: { icon: ShoppingBag, eyebrow: "Explore templates", title: "Marketplace", description: "Start faster with thoughtful templates for work and life." },
    Help: { icon: CircleHelp, eyebrow: "Support center", title: "Help", description: "Find answers and learn how to get more from your workspace." },
  }[type];
  const Icon = config.icon;
  return <main className="flex-1 overflow-y-auto bg-background text-foreground"><div className="mx-auto max-w-5xl px-6 py-10 sm:px-12 sm:py-14"><button onClick={onBack} className="mb-10 flex items-center gap-2 text-xs font-medium text-muted-foreground transition hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" />Back to workspace</button><div className="mb-10 flex items-start gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-accent"><Icon className="h-5 w-5 text-foreground" /></div><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">{config.eyebrow}</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{config.title}</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">{config.description}</p></div></div>{type === "Library" && <LibraryContent />}{type === "My Tasks" && <TasksContent />}{type === "Marketplace" && <MarketplaceContent />}{type === "Help" && <HelpContent />}</div></main>;
}

function LibraryContent() { return <><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-semibold">Your resources</h2><button className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">New resource</button></div><div className="grid gap-4 sm:grid-cols-3">{[[FileText,"Writing guide","A clean place for notes and ideas."],[LayoutTemplate,"Project brief","Plan a project from first idea to launch."],[Sparkles,"AI playbook","Prompts and workflows for everyday work."]].map(([I,title,desc]) => <div key={String(title)} className="group rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-0.5 hover:border-foreground/20"><I className="mb-8 h-5 w-5 text-muted-foreground group-hover:text-purple-500" /><h3 className="text-sm font-semibold">{String(title)}</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{String(desc)}</p><button className="mt-5 flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-foreground">Open <ChevronRight className="h-3 w-3" /></button></div>)}</div></>; }
function TasksContent() { return <><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-semibold">Today</h2><span className="text-xs text-muted-foreground">3 tasks</span></div><div className="space-y-2">{[["Finish the meeting notes","Today","high"],["Review workspace settings","Today","normal"],["Plan next sprint","Tomorrow","normal"]].map(([task,due,priority]) => <div key={task} className="flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3"><button className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md border border-border hover:border-primary"><Check className="h-3 w-3 opacity-0 hover:opacity-100" /></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground"><Clock3 className="h-3 w-3" />{due}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${priority === "high" ? "bg-red-500/10 text-red-500" : "bg-accent text-muted-foreground"}`}>{priority}</span></div>)}</div><button className="mt-5 rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-accent">Add task</button></>; }
function MarketplaceContent() { return <><div className="mb-5 flex items-center gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><input className="w-full rounded-lg border border-border bg-card py-2 pl-9 pr-3 text-sm outline-none focus:border-primary" placeholder="Search templates" /></div><button className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-accent">Categories</button></div><div className="grid gap-4 sm:grid-cols-3">{[["Meeting notes","Structure productive meetings"],["Project roadmap","Keep milestones visible"],["Personal dashboard","Organize your everyday life"]].map(([title,desc],i) => <div key={title} className="overflow-hidden rounded-2xl border border-border bg-card"><div className={`h-24 ${i===0?"bg-blue-500/20":i===1?"bg-purple-500/20":"bg-emerald-500/20"}`} /><div className="p-4"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{desc}</p><button className="mt-4 w-full rounded-lg bg-accent py-2 text-xs font-semibold hover:bg-accent/70">Use template</button></div></div>)}</div></>; }
function HelpContent() { return <><div className="relative mb-8 max-w-2xl"><Search className="absolute left-4 top-3.5 h-4 w-4 text-muted-foreground" /><input className="w-full rounded-xl border border-border bg-card py-3 pl-11 pr-4 text-sm outline-none focus:border-primary" placeholder="Search help articles" /></div><div className="grid gap-3 sm:grid-cols-2">{[["Getting started","Learn the basics of pages, blocks, and slash commands."],["Writing and editing","Use shortcuts, formatting, lists, and code blocks."],["AI Meeting Notes","Record, transcribe, and summarize a meeting."],["Account and billing","Manage your profile, password, plan, and connections."]].map(([title,desc]) => <button key={title} className="rounded-2xl border border-border bg-card p-5 text-left transition hover:border-foreground/20 hover:bg-accent"><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{desc}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-muted-foreground">Read article <ChevronRight className="h-3 w-3" /></span></button>)}</div></>; }